#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Eprogram")]
	public partial class EprogramDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertSyllabusSchedule(SyllabusSchedule instance);
    partial void UpdateSyllabusSchedule(SyllabusSchedule instance);
    partial void DeleteSyllabusSchedule(SyllabusSchedule instance);
    partial void InsertMapping(Mapping instance);
    partial void UpdateMapping(Mapping instance);
    partial void DeleteMapping(Mapping instance);
    partial void InsertProgram(Program instance);
    partial void UpdateProgram(Program instance);
    partial void DeleteProgram(Program instance);
    partial void InsertProgramOutcome(ProgramOutcome instance);
    partial void UpdateProgramOutcome(ProgramOutcome instance);
    partial void DeleteProgramOutcome(ProgramOutcome instance);
    partial void InsertSyllabus(Syllabus instance);
    partial void UpdateSyllabus(Syllabus instance);
    partial void DeleteSyllabus(Syllabus instance);
    partial void InsertSyllabusObjective(SyllabusObjective instance);
    partial void UpdateSyllabusObjective(SyllabusObjective instance);
    partial void DeleteSyllabusObjective(SyllabusObjective instance);
    partial void InsertSyllabusOutcome(SyllabusOutcome instance);
    partial void UpdateSyllabusOutcome(SyllabusOutcome instance);
    partial void DeleteSyllabusOutcome(SyllabusOutcome instance);
    #endregion
		
		public EprogramDataContext() : 
				base(global::DAL.Properties.Settings.Default.EprogramConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public EprogramDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EprogramDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EprogramDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EprogramDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<SyllabusSchedule> SyllabusSchedules
		{
			get
			{
				return this.GetTable<SyllabusSchedule>();
			}
		}
		
		public System.Data.Linq.Table<Mapping> Mappings
		{
			get
			{
				return this.GetTable<Mapping>();
			}
		}
		
		public System.Data.Linq.Table<Program> Programs
		{
			get
			{
				return this.GetTable<Program>();
			}
		}
		
		public System.Data.Linq.Table<ProgramOutcome> ProgramOutcomes
		{
			get
			{
				return this.GetTable<ProgramOutcome>();
			}
		}
		
		public System.Data.Linq.Table<Syllabus> Syllabus
		{
			get
			{
				return this.GetTable<Syllabus>();
			}
		}
		
		public System.Data.Linq.Table<SyllabusObjective> SyllabusObjectives
		{
			get
			{
				return this.GetTable<SyllabusObjective>();
			}
		}
		
		public System.Data.Linq.Table<SyllabusOutcome> SyllabusOutcomes
		{
			get
			{
				return this.GetTable<SyllabusOutcome>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _email;
		
		private string _name;
		
		private string _password;
		
		private System.Nullable<bool> _isAdmin;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnisAdminChanging(System.Nullable<bool> value);
    partial void OnisAdminChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit")]
		public System.Nullable<bool> isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SyllabusSchedule")]
	public partial class SyllabusSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idSyllabus;
		
		private System.Nullable<System.DateTime> _Day;
		
		private System.Nullable<int> _NumberPeriods;
		
		private string _LectureContent;
		
		private string _Activites;
		
		private string _Doc;
		
		private System.Nullable<bool> _mid;
		
		private EntityRef<Syllabus> _Syllabus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidSyllabusChanging(string value);
    partial void OnidSyllabusChanged();
    partial void OnDayChanging(System.Nullable<System.DateTime> value);
    partial void OnDayChanged();
    partial void OnNumberPeriodsChanging(System.Nullable<int> value);
    partial void OnNumberPeriodsChanged();
    partial void OnLectureContentChanging(string value);
    partial void OnLectureContentChanged();
    partial void OnActivitesChanging(string value);
    partial void OnActivitesChanged();
    partial void OnDocChanging(string value);
    partial void OnDocChanged();
    partial void OnmidChanging(System.Nullable<bool> value);
    partial void OnmidChanged();
    #endregion
		
		public SyllabusSchedule()
		{
			this._Syllabus = default(EntityRef<Syllabus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSyllabus", DbType="VarChar(10)")]
		public string idSyllabus
		{
			get
			{
				return this._idSyllabus;
			}
			set
			{
				if ((this._idSyllabus != value))
				{
					if (this._Syllabus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSyllabusChanging(value);
					this.SendPropertyChanging();
					this._idSyllabus = value;
					this.SendPropertyChanged("idSyllabus");
					this.OnidSyllabusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Date")]
		public System.Nullable<System.DateTime> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberPeriods", DbType="Int")]
		public System.Nullable<int> NumberPeriods
		{
			get
			{
				return this._NumberPeriods;
			}
			set
			{
				if ((this._NumberPeriods != value))
				{
					this.OnNumberPeriodsChanging(value);
					this.SendPropertyChanging();
					this._NumberPeriods = value;
					this.SendPropertyChanged("NumberPeriods");
					this.OnNumberPeriodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LectureContent", DbType="NVarChar(MAX)")]
		public string LectureContent
		{
			get
			{
				return this._LectureContent;
			}
			set
			{
				if ((this._LectureContent != value))
				{
					this.OnLectureContentChanging(value);
					this.SendPropertyChanging();
					this._LectureContent = value;
					this.SendPropertyChanged("LectureContent");
					this.OnLectureContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activites", DbType="NVarChar(MAX)")]
		public string Activites
		{
			get
			{
				return this._Activites;
			}
			set
			{
				if ((this._Activites != value))
				{
					this.OnActivitesChanging(value);
					this.SendPropertyChanging();
					this._Activites = value;
					this.SendPropertyChanged("Activites");
					this.OnActivitesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc", DbType="NVarChar(MAX)")]
		public string Doc
		{
			get
			{
				return this._Doc;
			}
			set
			{
				if ((this._Doc != value))
				{
					this.OnDocChanging(value);
					this.SendPropertyChanging();
					this._Doc = value;
					this.SendPropertyChanged("Doc");
					this.OnDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", DbType="Bit")]
		public System.Nullable<bool> mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				if ((this._mid != value))
				{
					this.OnmidChanging(value);
					this.SendPropertyChanging();
					this._mid = value;
					this.SendPropertyChanged("mid");
					this.OnmidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusSchedule", Storage="_Syllabus", ThisKey="idSyllabus", OtherKey="id", IsForeignKey=true)]
		public Syllabus Syllabus
		{
			get
			{
				return this._Syllabus.Entity;
			}
			set
			{
				Syllabus previousValue = this._Syllabus.Entity;
				if (((previousValue != value) 
							|| (this._Syllabus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Syllabus.Entity = null;
						previousValue.SyllabusSchedules.Remove(this);
					}
					this._Syllabus.Entity = value;
					if ((value != null))
					{
						value.SyllabusSchedules.Add(this);
						this._idSyllabus = value.id;
					}
					else
					{
						this._idSyllabus = default(string);
					}
					this.SendPropertyChanged("Syllabus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mapping")]
	public partial class Mapping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idSyllabus;
		
		private string _SyllabusOutcome;
		
		private string _Methods;
		
		private string _FirstPart;
		
		private System.Nullable<int> _FirstPercent;
		
		private string _SecondPart;
		
		private System.Nullable<int> _SecondPercent;
		
		private string _ThirdPart;
		
		private System.Nullable<int> _ThirdPercent;
		
		private string _ProgramOutcome;
		
		private System.Nullable<int> _desity;
		
		private EntityRef<Syllabus> _Syllabus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidSyllabusChanging(string value);
    partial void OnidSyllabusChanged();
    partial void OnSyllabusOutcomeChanging(string value);
    partial void OnSyllabusOutcomeChanged();
    partial void OnMethodsChanging(string value);
    partial void OnMethodsChanged();
    partial void OnFirstPartChanging(string value);
    partial void OnFirstPartChanged();
    partial void OnFirstPercentChanging(System.Nullable<int> value);
    partial void OnFirstPercentChanged();
    partial void OnSecondPartChanging(string value);
    partial void OnSecondPartChanged();
    partial void OnSecondPercentChanging(System.Nullable<int> value);
    partial void OnSecondPercentChanged();
    partial void OnThirdPartChanging(string value);
    partial void OnThirdPartChanged();
    partial void OnThirdPercentChanging(System.Nullable<int> value);
    partial void OnThirdPercentChanged();
    partial void OnProgramOutcomeChanging(string value);
    partial void OnProgramOutcomeChanged();
    partial void OndesityChanging(System.Nullable<int> value);
    partial void OndesityChanged();
    #endregion
		
		public Mapping()
		{
			this._Syllabus = default(EntityRef<Syllabus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSyllabus", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string idSyllabus
		{
			get
			{
				return this._idSyllabus;
			}
			set
			{
				if ((this._idSyllabus != value))
				{
					if (this._Syllabus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSyllabusChanging(value);
					this.SendPropertyChanging();
					this._idSyllabus = value;
					this.SendPropertyChanged("idSyllabus");
					this.OnidSyllabusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyllabusOutcome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SyllabusOutcome
		{
			get
			{
				return this._SyllabusOutcome;
			}
			set
			{
				if ((this._SyllabusOutcome != value))
				{
					this.OnSyllabusOutcomeChanging(value);
					this.SendPropertyChanging();
					this._SyllabusOutcome = value;
					this.SendPropertyChanged("SyllabusOutcome");
					this.OnSyllabusOutcomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Methods", DbType="NVarChar(MAX)")]
		public string Methods
		{
			get
			{
				return this._Methods;
			}
			set
			{
				if ((this._Methods != value))
				{
					this.OnMethodsChanging(value);
					this.SendPropertyChanging();
					this._Methods = value;
					this.SendPropertyChanged("Methods");
					this.OnMethodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstPart", DbType="NVarChar(100)")]
		public string FirstPart
		{
			get
			{
				return this._FirstPart;
			}
			set
			{
				if ((this._FirstPart != value))
				{
					this.OnFirstPartChanging(value);
					this.SendPropertyChanging();
					this._FirstPart = value;
					this.SendPropertyChanged("FirstPart");
					this.OnFirstPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstPercent", DbType="Int")]
		public System.Nullable<int> FirstPercent
		{
			get
			{
				return this._FirstPercent;
			}
			set
			{
				if ((this._FirstPercent != value))
				{
					this.OnFirstPercentChanging(value);
					this.SendPropertyChanging();
					this._FirstPercent = value;
					this.SendPropertyChanged("FirstPercent");
					this.OnFirstPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondPart", DbType="NVarChar(100)")]
		public string SecondPart
		{
			get
			{
				return this._SecondPart;
			}
			set
			{
				if ((this._SecondPart != value))
				{
					this.OnSecondPartChanging(value);
					this.SendPropertyChanging();
					this._SecondPart = value;
					this.SendPropertyChanged("SecondPart");
					this.OnSecondPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondPercent", DbType="Int")]
		public System.Nullable<int> SecondPercent
		{
			get
			{
				return this._SecondPercent;
			}
			set
			{
				if ((this._SecondPercent != value))
				{
					this.OnSecondPercentChanging(value);
					this.SendPropertyChanging();
					this._SecondPercent = value;
					this.SendPropertyChanged("SecondPercent");
					this.OnSecondPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdPart", DbType="NVarChar(100)")]
		public string ThirdPart
		{
			get
			{
				return this._ThirdPart;
			}
			set
			{
				if ((this._ThirdPart != value))
				{
					this.OnThirdPartChanging(value);
					this.SendPropertyChanging();
					this._ThirdPart = value;
					this.SendPropertyChanged("ThirdPart");
					this.OnThirdPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdPercent", DbType="Int")]
		public System.Nullable<int> ThirdPercent
		{
			get
			{
				return this._ThirdPercent;
			}
			set
			{
				if ((this._ThirdPercent != value))
				{
					this.OnThirdPercentChanging(value);
					this.SendPropertyChanging();
					this._ThirdPercent = value;
					this.SendPropertyChanged("ThirdPercent");
					this.OnThirdPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramOutcome", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProgramOutcome
		{
			get
			{
				return this._ProgramOutcome;
			}
			set
			{
				if ((this._ProgramOutcome != value))
				{
					this.OnProgramOutcomeChanging(value);
					this.SendPropertyChanging();
					this._ProgramOutcome = value;
					this.SendPropertyChanged("ProgramOutcome");
					this.OnProgramOutcomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desity", DbType="Int")]
		public System.Nullable<int> desity
		{
			get
			{
				return this._desity;
			}
			set
			{
				if ((this._desity != value))
				{
					this.OndesityChanging(value);
					this.SendPropertyChanging();
					this._desity = value;
					this.SendPropertyChanged("desity");
					this.OndesityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_Mapping", Storage="_Syllabus", ThisKey="idSyllabus", OtherKey="id", IsForeignKey=true)]
		public Syllabus Syllabus
		{
			get
			{
				return this._Syllabus.Entity;
			}
			set
			{
				Syllabus previousValue = this._Syllabus.Entity;
				if (((previousValue != value) 
							|| (this._Syllabus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Syllabus.Entity = null;
						previousValue.Mappings.Remove(this);
					}
					this._Syllabus.Entity = value;
					if ((value != null))
					{
						value.Mappings.Add(this);
						this._idSyllabus = value.id;
					}
					else
					{
						this._idSyllabus = default(string);
					}
					this.SendPropertyChanged("Syllabus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Program")]
	public partial class Program : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private string _idAccount;
		
		private string _ProgramLevel;
		
		private string _ProgramBranch;
		
		private string _ProgramType;
		
		private string _ProgramTime;
		
		private string _ProgramActor;
		
		private string _ProgramVolume;
		
		private string _ProgramProcess;
		
		private System.Nullable<int> _ProgramSemester;
		
		private System.Nullable<int> _ProgramTC;
		
		private System.Nullable<int> _ProgramPoint;
		
		private string _ProgramLecturer;
		
		private string _ProgramPackage;
		
		private System.Nullable<bool> _isLock;
		
		private EntitySet<ProgramOutcome> _ProgramOutcomes;
		
		private EntitySet<Syllabus> _Syllabus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnidAccountChanging(string value);
    partial void OnidAccountChanged();
    partial void OnProgramLevelChanging(string value);
    partial void OnProgramLevelChanged();
    partial void OnProgramBranchChanging(string value);
    partial void OnProgramBranchChanged();
    partial void OnProgramTypeChanging(string value);
    partial void OnProgramTypeChanged();
    partial void OnProgramTimeChanging(string value);
    partial void OnProgramTimeChanged();
    partial void OnProgramActorChanging(string value);
    partial void OnProgramActorChanged();
    partial void OnProgramVolumeChanging(string value);
    partial void OnProgramVolumeChanged();
    partial void OnProgramProcessChanging(string value);
    partial void OnProgramProcessChanged();
    partial void OnProgramSemesterChanging(System.Nullable<int> value);
    partial void OnProgramSemesterChanged();
    partial void OnProgramTCChanging(System.Nullable<int> value);
    partial void OnProgramTCChanged();
    partial void OnProgramPointChanging(System.Nullable<int> value);
    partial void OnProgramPointChanged();
    partial void OnProgramLecturerChanging(string value);
    partial void OnProgramLecturerChanged();
    partial void OnProgramPackageChanging(string value);
    partial void OnProgramPackageChanged();
    partial void OnisLockChanging(System.Nullable<bool> value);
    partial void OnisLockChanged();
    #endregion
		
		public Program()
		{
			this._ProgramOutcomes = new EntitySet<ProgramOutcome>(new Action<ProgramOutcome>(this.attach_ProgramOutcomes), new Action<ProgramOutcome>(this.detach_ProgramOutcomes));
			this._Syllabus = new EntitySet<Syllabus>(new Action<Syllabus>(this.attach_Syllabus), new Action<Syllabus>(this.detach_Syllabus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAccount", DbType="VarChar(7)")]
		public string idAccount
		{
			get
			{
				return this._idAccount;
			}
			set
			{
				if ((this._idAccount != value))
				{
					this.OnidAccountChanging(value);
					this.SendPropertyChanging();
					this._idAccount = value;
					this.SendPropertyChanged("idAccount");
					this.OnidAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramLevel", DbType="NVarChar(100)")]
		public string ProgramLevel
		{
			get
			{
				return this._ProgramLevel;
			}
			set
			{
				if ((this._ProgramLevel != value))
				{
					this.OnProgramLevelChanging(value);
					this.SendPropertyChanging();
					this._ProgramLevel = value;
					this.SendPropertyChanged("ProgramLevel");
					this.OnProgramLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramBranch", DbType="NVarChar(100)")]
		public string ProgramBranch
		{
			get
			{
				return this._ProgramBranch;
			}
			set
			{
				if ((this._ProgramBranch != value))
				{
					this.OnProgramBranchChanging(value);
					this.SendPropertyChanging();
					this._ProgramBranch = value;
					this.SendPropertyChanged("ProgramBranch");
					this.OnProgramBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramType", DbType="NVarChar(100)")]
		public string ProgramType
		{
			get
			{
				return this._ProgramType;
			}
			set
			{
				if ((this._ProgramType != value))
				{
					this.OnProgramTypeChanging(value);
					this.SendPropertyChanging();
					this._ProgramType = value;
					this.SendPropertyChanged("ProgramType");
					this.OnProgramTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramTime", DbType="NVarChar(100)")]
		public string ProgramTime
		{
			get
			{
				return this._ProgramTime;
			}
			set
			{
				if ((this._ProgramTime != value))
				{
					this.OnProgramTimeChanging(value);
					this.SendPropertyChanging();
					this._ProgramTime = value;
					this.SendPropertyChanged("ProgramTime");
					this.OnProgramTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramActor", DbType="NVarChar(100)")]
		public string ProgramActor
		{
			get
			{
				return this._ProgramActor;
			}
			set
			{
				if ((this._ProgramActor != value))
				{
					this.OnProgramActorChanging(value);
					this.SendPropertyChanging();
					this._ProgramActor = value;
					this.SendPropertyChanged("ProgramActor");
					this.OnProgramActorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramVolume", DbType="NVarChar(100)")]
		public string ProgramVolume
		{
			get
			{
				return this._ProgramVolume;
			}
			set
			{
				if ((this._ProgramVolume != value))
				{
					this.OnProgramVolumeChanging(value);
					this.SendPropertyChanging();
					this._ProgramVolume = value;
					this.SendPropertyChanged("ProgramVolume");
					this.OnProgramVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramProcess", DbType="NVarChar(100)")]
		public string ProgramProcess
		{
			get
			{
				return this._ProgramProcess;
			}
			set
			{
				if ((this._ProgramProcess != value))
				{
					this.OnProgramProcessChanging(value);
					this.SendPropertyChanging();
					this._ProgramProcess = value;
					this.SendPropertyChanged("ProgramProcess");
					this.OnProgramProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramSemester", DbType="Int")]
		public System.Nullable<int> ProgramSemester
		{
			get
			{
				return this._ProgramSemester;
			}
			set
			{
				if ((this._ProgramSemester != value))
				{
					this.OnProgramSemesterChanging(value);
					this.SendPropertyChanging();
					this._ProgramSemester = value;
					this.SendPropertyChanged("ProgramSemester");
					this.OnProgramSemesterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramTC", DbType="Int")]
		public System.Nullable<int> ProgramTC
		{
			get
			{
				return this._ProgramTC;
			}
			set
			{
				if ((this._ProgramTC != value))
				{
					this.OnProgramTCChanging(value);
					this.SendPropertyChanging();
					this._ProgramTC = value;
					this.SendPropertyChanged("ProgramTC");
					this.OnProgramTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramPoint", DbType="Int")]
		public System.Nullable<int> ProgramPoint
		{
			get
			{
				return this._ProgramPoint;
			}
			set
			{
				if ((this._ProgramPoint != value))
				{
					this.OnProgramPointChanging(value);
					this.SendPropertyChanging();
					this._ProgramPoint = value;
					this.SendPropertyChanged("ProgramPoint");
					this.OnProgramPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramLecturer", DbType="NVarChar(MAX)")]
		public string ProgramLecturer
		{
			get
			{
				return this._ProgramLecturer;
			}
			set
			{
				if ((this._ProgramLecturer != value))
				{
					this.OnProgramLecturerChanging(value);
					this.SendPropertyChanging();
					this._ProgramLecturer = value;
					this.SendPropertyChanged("ProgramLecturer");
					this.OnProgramLecturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramPackage", DbType="NVarChar(MAX)")]
		public string ProgramPackage
		{
			get
			{
				return this._ProgramPackage;
			}
			set
			{
				if ((this._ProgramPackage != value))
				{
					this.OnProgramPackageChanging(value);
					this.SendPropertyChanging();
					this._ProgramPackage = value;
					this.SendPropertyChanged("ProgramPackage");
					this.OnProgramPackageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isLock", DbType="Bit")]
		public System.Nullable<bool> isLock
		{
			get
			{
				return this._isLock;
			}
			set
			{
				if ((this._isLock != value))
				{
					this.OnisLockChanging(value);
					this.SendPropertyChanging();
					this._isLock = value;
					this.SendPropertyChanged("isLock");
					this.OnisLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_ProgramOutcome", Storage="_ProgramOutcomes", ThisKey="id", OtherKey="idProgram")]
		public EntitySet<ProgramOutcome> ProgramOutcomes
		{
			get
			{
				return this._ProgramOutcomes;
			}
			set
			{
				this._ProgramOutcomes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_Syllabus", Storage="_Syllabus", ThisKey="id", OtherKey="idProgram")]
		public EntitySet<Syllabus> Syllabus
		{
			get
			{
				return this._Syllabus;
			}
			set
			{
				this._Syllabus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProgramOutcomes(ProgramOutcome entity)
		{
			this.SendPropertyChanging();
			entity.Program = this;
		}
		
		private void detach_ProgramOutcomes(ProgramOutcome entity)
		{
			this.SendPropertyChanging();
			entity.Program = null;
		}
		
		private void attach_Syllabus(Syllabus entity)
		{
			this.SendPropertyChanging();
			entity.Program = this;
		}
		
		private void detach_Syllabus(Syllabus entity)
		{
			this.SendPropertyChanging();
			entity.Program = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProgramOutcomes")]
	public partial class ProgramOutcome : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idProgram;
		
		private System.Nullable<int> _OutcomeType;
		
		private string _OutcomeNo;
		
		private string _OutcomeContent;
		
		private EntityRef<Program> _Program;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidProgramChanging(string value);
    partial void OnidProgramChanged();
    partial void OnOutcomeTypeChanging(System.Nullable<int> value);
    partial void OnOutcomeTypeChanged();
    partial void OnOutcomeNoChanging(string value);
    partial void OnOutcomeNoChanged();
    partial void OnOutcomeContentChanging(string value);
    partial void OnOutcomeContentChanged();
    #endregion
		
		public ProgramOutcome()
		{
			this._Program = default(EntityRef<Program>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProgram", DbType="VarChar(6)")]
		public string idProgram
		{
			get
			{
				return this._idProgram;
			}
			set
			{
				if ((this._idProgram != value))
				{
					if (this._Program.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProgramChanging(value);
					this.SendPropertyChanging();
					this._idProgram = value;
					this.SendPropertyChanged("idProgram");
					this.OnidProgramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutcomeType", DbType="Int")]
		public System.Nullable<int> OutcomeType
		{
			get
			{
				return this._OutcomeType;
			}
			set
			{
				if ((this._OutcomeType != value))
				{
					this.OnOutcomeTypeChanging(value);
					this.SendPropertyChanging();
					this._OutcomeType = value;
					this.SendPropertyChanged("OutcomeType");
					this.OnOutcomeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutcomeNo", DbType="NVarChar(50)")]
		public string OutcomeNo
		{
			get
			{
				return this._OutcomeNo;
			}
			set
			{
				if ((this._OutcomeNo != value))
				{
					this.OnOutcomeNoChanging(value);
					this.SendPropertyChanging();
					this._OutcomeNo = value;
					this.SendPropertyChanged("OutcomeNo");
					this.OnOutcomeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutcomeContent", DbType="NVarChar(MAX)")]
		public string OutcomeContent
		{
			get
			{
				return this._OutcomeContent;
			}
			set
			{
				if ((this._OutcomeContent != value))
				{
					this.OnOutcomeContentChanging(value);
					this.SendPropertyChanging();
					this._OutcomeContent = value;
					this.SendPropertyChanged("OutcomeContent");
					this.OnOutcomeContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_ProgramOutcome", Storage="_Program", ThisKey="idProgram", OtherKey="id", IsForeignKey=true)]
		public Program Program
		{
			get
			{
				return this._Program.Entity;
			}
			set
			{
				Program previousValue = this._Program.Entity;
				if (((previousValue != value) 
							|| (this._Program.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Program.Entity = null;
						previousValue.ProgramOutcomes.Remove(this);
					}
					this._Program.Entity = value;
					if ((value != null))
					{
						value.ProgramOutcomes.Add(this);
						this._idProgram = value.id;
					}
					else
					{
						this._idProgram = default(string);
					}
					this.SendPropertyChanged("Program");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Syllabus")]
	public partial class Syllabus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idProgram;
		
		private string _name;
		
		private System.Nullable<int> _CourseType;
		
		private System.Nullable<int> _CoursePoint;
		
		private System.Nullable<int> _CourseSemester;
		
		private string _CourseCode;
		
		private string _PreCourse;
		
		private string _CourseContent;
		
		private string _CourseLecturer;
		
		private string _CourseLevel;
		
		private string _CourseTime;
		
		private string _CourseDescription;
		
		private string _CourseDocument;
		
		private string _CourseMethod;
		
		private string _CourseRequest;
		
		private string _idAccount;
		
		private System.Nullable<bool> _isLockEdit;
		
		private System.Nullable<int> _CourseLT;
		
		private EntitySet<SyllabusSchedule> _SyllabusSchedules;
		
		private EntitySet<Mapping> _Mappings;
		
		private EntitySet<SyllabusObjective> _SyllabusObjectives;
		
		private EntitySet<SyllabusOutcome> _SyllabusOutcomes;
		
		private EntityRef<Program> _Program;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidProgramChanging(string value);
    partial void OnidProgramChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnCourseTypeChanging(System.Nullable<int> value);
    partial void OnCourseTypeChanged();
    partial void OnCoursePointChanging(System.Nullable<int> value);
    partial void OnCoursePointChanged();
    partial void OnCourseSemesterChanging(System.Nullable<int> value);
    partial void OnCourseSemesterChanged();
    partial void OnCourseCodeChanging(string value);
    partial void OnCourseCodeChanged();
    partial void OnPreCourseChanging(string value);
    partial void OnPreCourseChanged();
    partial void OnCourseContentChanging(string value);
    partial void OnCourseContentChanged();
    partial void OnCourseLecturerChanging(string value);
    partial void OnCourseLecturerChanged();
    partial void OnCourseLevelChanging(string value);
    partial void OnCourseLevelChanged();
    partial void OnCourseTimeChanging(string value);
    partial void OnCourseTimeChanged();
    partial void OnCourseDescriptionChanging(string value);
    partial void OnCourseDescriptionChanged();
    partial void OnCourseDocumentChanging(string value);
    partial void OnCourseDocumentChanged();
    partial void OnCourseMethodChanging(string value);
    partial void OnCourseMethodChanged();
    partial void OnCourseRequestChanging(string value);
    partial void OnCourseRequestChanged();
    partial void OnidAccountChanging(string value);
    partial void OnidAccountChanged();
    partial void OnisLockEditChanging(System.Nullable<bool> value);
    partial void OnisLockEditChanged();
    partial void OnCourseLTChanging(System.Nullable<int> value);
    partial void OnCourseLTChanged();
    #endregion
		
		public Syllabus()
		{
			this._SyllabusSchedules = new EntitySet<SyllabusSchedule>(new Action<SyllabusSchedule>(this.attach_SyllabusSchedules), new Action<SyllabusSchedule>(this.detach_SyllabusSchedules));
			this._Mappings = new EntitySet<Mapping>(new Action<Mapping>(this.attach_Mappings), new Action<Mapping>(this.detach_Mappings));
			this._SyllabusObjectives = new EntitySet<SyllabusObjective>(new Action<SyllabusObjective>(this.attach_SyllabusObjectives), new Action<SyllabusObjective>(this.detach_SyllabusObjectives));
			this._SyllabusOutcomes = new EntitySet<SyllabusOutcome>(new Action<SyllabusOutcome>(this.attach_SyllabusOutcomes), new Action<SyllabusOutcome>(this.detach_SyllabusOutcomes));
			this._Program = default(EntityRef<Program>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProgram", DbType="VarChar(6)")]
		public string idProgram
		{
			get
			{
				return this._idProgram;
			}
			set
			{
				if ((this._idProgram != value))
				{
					if (this._Program.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidProgramChanging(value);
					this.SendPropertyChanging();
					this._idProgram = value;
					this.SendPropertyChanged("idProgram");
					this.OnidProgramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseType", DbType="Int")]
		public System.Nullable<int> CourseType
		{
			get
			{
				return this._CourseType;
			}
			set
			{
				if ((this._CourseType != value))
				{
					this.OnCourseTypeChanging(value);
					this.SendPropertyChanging();
					this._CourseType = value;
					this.SendPropertyChanged("CourseType");
					this.OnCourseTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoursePoint", DbType="Int")]
		public System.Nullable<int> CoursePoint
		{
			get
			{
				return this._CoursePoint;
			}
			set
			{
				if ((this._CoursePoint != value))
				{
					this.OnCoursePointChanging(value);
					this.SendPropertyChanging();
					this._CoursePoint = value;
					this.SendPropertyChanged("CoursePoint");
					this.OnCoursePointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseSemester", DbType="Int")]
		public System.Nullable<int> CourseSemester
		{
			get
			{
				return this._CourseSemester;
			}
			set
			{
				if ((this._CourseSemester != value))
				{
					this.OnCourseSemesterChanging(value);
					this.SendPropertyChanging();
					this._CourseSemester = value;
					this.SendPropertyChanged("CourseSemester");
					this.OnCourseSemesterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseCode", DbType="VarChar(10)")]
		public string CourseCode
		{
			get
			{
				return this._CourseCode;
			}
			set
			{
				if ((this._CourseCode != value))
				{
					this.OnCourseCodeChanging(value);
					this.SendPropertyChanging();
					this._CourseCode = value;
					this.SendPropertyChanged("CourseCode");
					this.OnCourseCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreCourse", DbType="NVarChar(100)")]
		public string PreCourse
		{
			get
			{
				return this._PreCourse;
			}
			set
			{
				if ((this._PreCourse != value))
				{
					this.OnPreCourseChanging(value);
					this.SendPropertyChanging();
					this._PreCourse = value;
					this.SendPropertyChanged("PreCourse");
					this.OnPreCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseContent", DbType="NVarChar(MAX)")]
		public string CourseContent
		{
			get
			{
				return this._CourseContent;
			}
			set
			{
				if ((this._CourseContent != value))
				{
					this.OnCourseContentChanging(value);
					this.SendPropertyChanging();
					this._CourseContent = value;
					this.SendPropertyChanged("CourseContent");
					this.OnCourseContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseLecturer", DbType="NVarChar(MAX)")]
		public string CourseLecturer
		{
			get
			{
				return this._CourseLecturer;
			}
			set
			{
				if ((this._CourseLecturer != value))
				{
					this.OnCourseLecturerChanging(value);
					this.SendPropertyChanging();
					this._CourseLecturer = value;
					this.SendPropertyChanged("CourseLecturer");
					this.OnCourseLecturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseLevel", DbType="NVarChar(100)")]
		public string CourseLevel
		{
			get
			{
				return this._CourseLevel;
			}
			set
			{
				if ((this._CourseLevel != value))
				{
					this.OnCourseLevelChanging(value);
					this.SendPropertyChanging();
					this._CourseLevel = value;
					this.SendPropertyChanged("CourseLevel");
					this.OnCourseLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseTime", DbType="NVarChar(100)")]
		public string CourseTime
		{
			get
			{
				return this._CourseTime;
			}
			set
			{
				if ((this._CourseTime != value))
				{
					this.OnCourseTimeChanging(value);
					this.SendPropertyChanging();
					this._CourseTime = value;
					this.SendPropertyChanged("CourseTime");
					this.OnCourseTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseDescription", DbType="NVarChar(MAX)")]
		public string CourseDescription
		{
			get
			{
				return this._CourseDescription;
			}
			set
			{
				if ((this._CourseDescription != value))
				{
					this.OnCourseDescriptionChanging(value);
					this.SendPropertyChanging();
					this._CourseDescription = value;
					this.SendPropertyChanged("CourseDescription");
					this.OnCourseDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseDocument", DbType="NVarChar(MAX)")]
		public string CourseDocument
		{
			get
			{
				return this._CourseDocument;
			}
			set
			{
				if ((this._CourseDocument != value))
				{
					this.OnCourseDocumentChanging(value);
					this.SendPropertyChanging();
					this._CourseDocument = value;
					this.SendPropertyChanged("CourseDocument");
					this.OnCourseDocumentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseMethod", DbType="NVarChar(MAX)")]
		public string CourseMethod
		{
			get
			{
				return this._CourseMethod;
			}
			set
			{
				if ((this._CourseMethod != value))
				{
					this.OnCourseMethodChanging(value);
					this.SendPropertyChanging();
					this._CourseMethod = value;
					this.SendPropertyChanged("CourseMethod");
					this.OnCourseMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseRequest", DbType="NVarChar(MAX)")]
		public string CourseRequest
		{
			get
			{
				return this._CourseRequest;
			}
			set
			{
				if ((this._CourseRequest != value))
				{
					this.OnCourseRequestChanging(value);
					this.SendPropertyChanging();
					this._CourseRequest = value;
					this.SendPropertyChanged("CourseRequest");
					this.OnCourseRequestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAccount", DbType="VarChar(7)")]
		public string idAccount
		{
			get
			{
				return this._idAccount;
			}
			set
			{
				if ((this._idAccount != value))
				{
					this.OnidAccountChanging(value);
					this.SendPropertyChanging();
					this._idAccount = value;
					this.SendPropertyChanged("idAccount");
					this.OnidAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isLockEdit", DbType="Bit")]
		public System.Nullable<bool> isLockEdit
		{
			get
			{
				return this._isLockEdit;
			}
			set
			{
				if ((this._isLockEdit != value))
				{
					this.OnisLockEditChanging(value);
					this.SendPropertyChanging();
					this._isLockEdit = value;
					this.SendPropertyChanged("isLockEdit");
					this.OnisLockEditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseLT", DbType="Int")]
		public System.Nullable<int> CourseLT
		{
			get
			{
				return this._CourseLT;
			}
			set
			{
				if ((this._CourseLT != value))
				{
					this.OnCourseLTChanging(value);
					this.SendPropertyChanging();
					this._CourseLT = value;
					this.SendPropertyChanged("CourseLT");
					this.OnCourseLTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusSchedule", Storage="_SyllabusSchedules", ThisKey="id", OtherKey="idSyllabus")]
		public EntitySet<SyllabusSchedule> SyllabusSchedules
		{
			get
			{
				return this._SyllabusSchedules;
			}
			set
			{
				this._SyllabusSchedules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_Mapping", Storage="_Mappings", ThisKey="id", OtherKey="idSyllabus")]
		public EntitySet<Mapping> Mappings
		{
			get
			{
				return this._Mappings;
			}
			set
			{
				this._Mappings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusObjective", Storage="_SyllabusObjectives", ThisKey="id", OtherKey="idSyllabus")]
		public EntitySet<SyllabusObjective> SyllabusObjectives
		{
			get
			{
				return this._SyllabusObjectives;
			}
			set
			{
				this._SyllabusObjectives.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusOutcome", Storage="_SyllabusOutcomes", ThisKey="id", OtherKey="idSyllabus")]
		public EntitySet<SyllabusOutcome> SyllabusOutcomes
		{
			get
			{
				return this._SyllabusOutcomes;
			}
			set
			{
				this._SyllabusOutcomes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_Syllabus", Storage="_Program", ThisKey="idProgram", OtherKey="id", IsForeignKey=true)]
		public Program Program
		{
			get
			{
				return this._Program.Entity;
			}
			set
			{
				Program previousValue = this._Program.Entity;
				if (((previousValue != value) 
							|| (this._Program.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Program.Entity = null;
						previousValue.Syllabus.Remove(this);
					}
					this._Program.Entity = value;
					if ((value != null))
					{
						value.Syllabus.Add(this);
						this._idProgram = value.id;
					}
					else
					{
						this._idProgram = default(string);
					}
					this.SendPropertyChanged("Program");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SyllabusSchedules(SyllabusSchedule entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = this;
		}
		
		private void detach_SyllabusSchedules(SyllabusSchedule entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = null;
		}
		
		private void attach_Mappings(Mapping entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = this;
		}
		
		private void detach_Mappings(Mapping entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = null;
		}
		
		private void attach_SyllabusObjectives(SyllabusObjective entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = this;
		}
		
		private void detach_SyllabusObjectives(SyllabusObjective entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = null;
		}
		
		private void attach_SyllabusOutcomes(SyllabusOutcome entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = this;
		}
		
		private void detach_SyllabusOutcomes(SyllabusOutcome entity)
		{
			this.SendPropertyChanging();
			entity.Syllabus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SyllabusObjectives")]
	public partial class SyllabusObjective : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idSyllabus;
		
		private string _ObjSContent;
		
		private EntityRef<Syllabus> _Syllabus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidSyllabusChanging(string value);
    partial void OnidSyllabusChanged();
    partial void OnObjSContentChanging(string value);
    partial void OnObjSContentChanged();
    #endregion
		
		public SyllabusObjective()
		{
			this._Syllabus = default(EntityRef<Syllabus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSyllabus", DbType="VarChar(10)")]
		public string idSyllabus
		{
			get
			{
				return this._idSyllabus;
			}
			set
			{
				if ((this._idSyllabus != value))
				{
					if (this._Syllabus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSyllabusChanging(value);
					this.SendPropertyChanging();
					this._idSyllabus = value;
					this.SendPropertyChanged("idSyllabus");
					this.OnidSyllabusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjSContent", DbType="NVarChar(MAX)")]
		public string ObjSContent
		{
			get
			{
				return this._ObjSContent;
			}
			set
			{
				if ((this._ObjSContent != value))
				{
					this.OnObjSContentChanging(value);
					this.SendPropertyChanging();
					this._ObjSContent = value;
					this.SendPropertyChanged("ObjSContent");
					this.OnObjSContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusObjective", Storage="_Syllabus", ThisKey="idSyllabus", OtherKey="id", IsForeignKey=true)]
		public Syllabus Syllabus
		{
			get
			{
				return this._Syllabus.Entity;
			}
			set
			{
				Syllabus previousValue = this._Syllabus.Entity;
				if (((previousValue != value) 
							|| (this._Syllabus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Syllabus.Entity = null;
						previousValue.SyllabusObjectives.Remove(this);
					}
					this._Syllabus.Entity = value;
					if ((value != null))
					{
						value.SyllabusObjectives.Add(this);
						this._idSyllabus = value.id;
					}
					else
					{
						this._idSyllabus = default(string);
					}
					this.SendPropertyChanged("Syllabus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SyllabusOutcomes")]
	public partial class SyllabusOutcome : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idSyllabus;
		
		private string _OutcomeNo;
		
		private string _OutcomeContent;
		
		private EntityRef<Syllabus> _Syllabus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidSyllabusChanging(string value);
    partial void OnidSyllabusChanged();
    partial void OnOutcomeNoChanging(string value);
    partial void OnOutcomeNoChanged();
    partial void OnOutcomeContentChanging(string value);
    partial void OnOutcomeContentChanged();
    #endregion
		
		public SyllabusOutcome()
		{
			this._Syllabus = default(EntityRef<Syllabus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSyllabus", DbType="VarChar(10)")]
		public string idSyllabus
		{
			get
			{
				return this._idSyllabus;
			}
			set
			{
				if ((this._idSyllabus != value))
				{
					if (this._Syllabus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSyllabusChanging(value);
					this.SendPropertyChanging();
					this._idSyllabus = value;
					this.SendPropertyChanged("idSyllabus");
					this.OnidSyllabusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutcomeNo", DbType="NVarChar(50)")]
		public string OutcomeNo
		{
			get
			{
				return this._OutcomeNo;
			}
			set
			{
				if ((this._OutcomeNo != value))
				{
					this.OnOutcomeNoChanging(value);
					this.SendPropertyChanging();
					this._OutcomeNo = value;
					this.SendPropertyChanged("OutcomeNo");
					this.OnOutcomeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutcomeContent", DbType="NVarChar(MAX)")]
		public string OutcomeContent
		{
			get
			{
				return this._OutcomeContent;
			}
			set
			{
				if ((this._OutcomeContent != value))
				{
					this.OnOutcomeContentChanging(value);
					this.SendPropertyChanging();
					this._OutcomeContent = value;
					this.SendPropertyChanged("OutcomeContent");
					this.OnOutcomeContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Syllabus_SyllabusOutcome", Storage="_Syllabus", ThisKey="idSyllabus", OtherKey="id", IsForeignKey=true)]
		public Syllabus Syllabus
		{
			get
			{
				return this._Syllabus.Entity;
			}
			set
			{
				Syllabus previousValue = this._Syllabus.Entity;
				if (((previousValue != value) 
							|| (this._Syllabus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Syllabus.Entity = null;
						previousValue.SyllabusOutcomes.Remove(this);
					}
					this._Syllabus.Entity = value;
					if ((value != null))
					{
						value.SyllabusOutcomes.Add(this);
						this._idSyllabus = value.id;
					}
					else
					{
						this._idSyllabus = default(string);
					}
					this.SendPropertyChanged("Syllabus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
